### ISSUE TITLE
GitHub DarkMode: Data Structure image is not displayed correctly

### ISSUE THREAD

**Issue by MaxBoehler** [FireDynamics/fdsreader#25]
Problem:
When browsing GitHub using dark mode the Data Structure image is not displayed correctly:
![image](https://user-images.githubusercontent.com/33684898/108331414-07ebe080-71cf-11eb-8231-6a800a7c4c5a.png)

Solution:
Fill background of attributes with white color as well.

Thanks.

**Comment by JanVogelsang** [comment]
Fixed in ec6e243
