### ISSUE TITLE
Package version dependencies

### ISSUE THREAD

**Issue by lu-kas** [FireDynamics/fdsreader#27]
Are the explicitly required package versions necessary?

E.g.:

fdsreader 0.9.12 requires docutils==0.16, but you'll have docutils 0.17 which is incompatible.
fdsreader 0.9.12 requires Pillow==8.1.0, but you'll have pillow 8.2.0 which is incompatible.
fdsreader 0.9.12 requires Pygments==2.8.0, but you'll have pygments 2.8.1 which is incompatible.
fdsreader 0.9.12 requires Sphinx==3.5.1, but you'll have sphinx 3.5.3 which is incompatible.

Fails to install in a newly setup environment.

**Comment by JanVogelsang** [comment]
Fixed in 90d57c3
