### ISSUE TITLE
Read FDS+Evac data

### ISSUE THREAD

**Issue by gjaeger** [FireDynamics/fdsreader#30]
Read Evac specific files:
- [x] converged evacuation flow fields (`CHID_evac.eff`)
- [x] smoke and gas concentration information from the FDS fire calculation (`CHID_evac.fed`)
- [x] agent trajectories and data (`CHID_evac_NM-NFM.prt5`) 

If you have any questions about the implementation, please do not hesitate to contact me.

**Comment by JanVogelsang** [comment]
Evacuation is now fully supported, however there is a bug in FDS at the moment which doesn't allow me to read in the evacuation-classes yet (pretty much only labels). Waiting for a fix: https://github.com/firemodels/fds/issues/9571

**Comment by gjaeger** [comment]
@JanVogelsang Many thanks for your work.

**Comment by JanVogelsang** [comment]
Hi @chenlinjie1213, I think your question is unrelated to this issue, right? If that is indeed the case, please open up a new issue. If that is not the case, please elaborate how the .plot3d-files are related to evacuation-data, as I have missed something here.

**Comment by chenlinjie1213** [comment]
Well, thank you.
I'm sorry, I should have started a separate discussion forum, thanks for the reminder.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FireDynamics/fdsreader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FireDynamics/fdsreader] Read FDS+Evac data (#30)





 
Hi @chenlinjie1213, I think your question is unrelated to this issue, right? If that is indeed the case, please open up a new issue. If that is not the case, please elaborate how the .plot3d-files are related to evacuation-data, as I have missed something here.

**Comment by chenlinjie1213** [comment]
Greetings, Professor, if FDS calculates the thermal radiation value of a point in space, is the grid size within the characteristic diameter of the fire source to be more accurate? Or does this rule not necessarily hold?


For example, if the characteristic diameter of the fire source calculated by the formula is 2m-8m, if a 1m grid and a 10m grid are used under the same working conditions, can we determine that the heat radiation value calculated by the 1m grid working condition is smaller?



THANKS A LOT.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FireDynamics/fdsreader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FireDynamics/fdsreader] Read FDS+Evac data (#30)





 
Hi @chenlinjie1213, I think your question is unrelated to this issue, right? If that is indeed the case, please open up a new issue. If that is not the case, please elaborate how the .plot3d-files are related to evacuation-data, as I have missed something here.
