### ISSUE TITLE
Extra faces at geom objects

### ISSUE THREAD

**Issue by jet5678** [FireDynamics/fdsreader#31]
[geom_example.ipynb.txt](https://github.com/FireDynamics/fdsreader/files/6478619/geom_example.ipynb.txt)
[Example_1.fds.txt](https://github.com/FireDynamics/fdsreader/files/6478623/Example_1.fds.txt)
![Screenshot 2021-05-14 132046](https://user-images.githubusercontent.com/50654162/118269016-74206c80-b4be-11eb-909b-67b4f0458177.png)

Hi,
I have noticed that the sum of the surfaces of all the faces does not match the surface of the actual object. I have manually calculated an area of 8.8 for the example and the sum of all faces are 10.35. 
In the image you can see that there are additional faces inside the tetrahedron that should not be there and are not displayed in Smokeview.

With best regards

**Comment by JanVogelsang** [comment]
Could not be recreated in the newest version, reopen if the issue persists.
