### ISSUE TITLE
Distinguish between DEVC ID and quantity

### ISSUE THREAD

**Issue by lu-kas** [FireDynamics/fdsreader#33]
The input line

&DEVC ID='T_1.0', XYZ=0.0, 0.0, 1.0, QUANTITY='TEMPERATURE' /

leads to 

'T_1.0': Device(name=T_1.0, position=(0.0, 0.0, 1.0), quantity=Quantity('T_1.0')

Although the quantity is not stored in the _devc.csv file, it is available in the .smv file:

DEVICE
 T_1.0 % TEMPERATURE     0.00000     0.00000     1.00000     0.00000     0.00000    -1.00000  0  0 % null

Could you please make the fdsreader devices consistent with the naming of FDS? Thanks!

**Comment by JanVogelsang** [comment]
Fixed in 7135649
