### ISSUE TITLE
Device Data Overview dict Should Contain the Unit

### ISSUE THREAD

**Issue by TristanHehnen** [FireDynamics/fdsreader#34]
When looking at the device data, i.e. `fdsreader.Simulation("path").device`, a dictionary is provided with an overview on the devices. It should also contain the unit for the quantity that is recorded. So basically cell 0 in the `*_devc.csv` for the respective device.

**Comment by TristanHehnen** [comment]
I see that this was already adressed in https://github.com/FireDynamics/fdsreader/issues/32

closed

**Comment by lu-kas** [comment]
@TristanHehnen checkout the RC (1.1.0rc1), it has already addressed this issue.

**Comment by TristanHehnen** [comment]
Thanks!
