### ISSUE TITLE
Device documentation

### ISSUE THREAD

**Issue by TristanHehnen** [FireDynamics/fdsreader#35]
Documentation about the devices is missing in the API documentation.

**Comment by JanVogelsang** [comment]
You can find documentation about devices over here:
https://firedynamics.github.io/fdsreader/utils.html

However, with the next Update devices will be moved to a separate page for easier access:
https://firedynamics.github.io/fdsreader/devc.html

**Comment by TristanHehnen** [comment]
Great, thanks!
