### ISSUE TITLE
Read FED slice

### ISSUE THREAD

**Issue by TomOsw** [FireDynamics/fdsreader#38]
Hello, thanks for your work, it is a great help for my postprocessing.

Is there any possibility or workaround to read the FED slice generated from Smokeview?
I tried to add it to the SMV File (with correct path and it works in SMV) but it gives me an an subslice with this error in the data field: 

![image](https://user-images.githubusercontent.com/9481420/126775841-c4456cbf-dcc4-42fa-b93f-c6c5ac40d572.png)

Thank you, 
Thomas

**Comment by JanVogelsang** [comment]
Hello Thomas, actually it should read in the FED slices automatically already.
However, I am not quite sure what you mean by "generated from Smokeview". I am not aware of SmokeView generating any data, could you explain that further?

Also, maybe you can attach your .fds input file so I can run your simulation myself and check if I am able to read the data you need.

**Comment by JanVogelsang** [comment]
By the way, did you check if you can't simply acces your data with `sim.evacs.fed_grid`?

**Comment by TomOsw** [comment]
The FED slice is calculated with the first opening of Smokeview out of these three slices:
![image](https://user-images.githubusercontent.com/9481420/126951257-540b9591-59e2-46bd-88d9-b6c1ed9ac527.png)

(It has the ending _fed.sf)

It is not in the slice collection and is also not mentioned in the SMV file (where you get the slice file locations i think?) 
After manually adding the entry, the slice is in the collection, but the i get the error mentioned above.

[My example file](https://drive.google.com/drive/folders/1ENcIkdfa2flvX9KFnGbD4DkK_tJiEktA?usp=sharing) (+ the simulation results **WITHOUT** the mentioned fed.sf so that you can see how it is generated after the first opening of .smv)

I have no EVAC data in most of my simulations but i will enable it, if that's a workaround.

Thank you for your help.

**Comment by TomOsw** [comment]
Forgot to mention that you have to load the slice "Fractional effective dose" in SMV to generate it.

**Comment by JanVogelsang** [comment]
Hm unfortunately I can not reproduce your error. I can successfully load the FED slice and plot the corresponding data.

SLCF     1 # STRUCTURED &     0   617     0    22     4     4 !      12
 example_1_3_fed.sf
 Fractional effective dose
 FED
 
By adding this snippet to the .smv-file, the slice gets loaded in correctly as 12th slice, try it out.

**Comment by TomOsw** [comment]
Thank you for looking into that.
I found my issue.
If you abort the simulation this FED slice gets corrupted (other slices worked flawlessly so i did not notice that before).

**Comment by JanVogelsang** [comment]
Good to know!
