### ISSUE TITLE
wrong name for the last element of the *_hrr.csv file

### ISSUE THREAD

**Issue by uprilion** [FireDynamics/fdsreader#40]
Hello,

First thank you for this tool, the ability to read slicefiles, bndf, 3D smoke and post-process then easily in python is quite exiting.
I came into this while writing a little parser for the *_hrr.csv file (aborted in favor of fdsreader of course)

I've been testing this a few minutes now and I encountered a little bug : the last element of the *_hrr.csv file should be "ZONE_2"  in my use case but is "ZONE_2\n" in sim.hrr

I'm very new at using python so I'd not risk a clone/pull request but the following modification of the function `_load_HRR_data` in simulation.py seems to be ok:
in line 956: `keys = infile.readline().split(',')` -> `keys = (infile.readline().replace(r'\n', '')).split(',')`

Thank you,
Silvio

**Comment by JanVogelsang** [comment]
Fixed in 3c393da
