### ISSUE TITLE
_devices variable not available any more

### ISSUE THREAD

**Issue by lu-kas** [FireDynamics/fdsreader#45]
Hi,

I think the load devices function is broken:

https://github.com/FireDynamics/fdsreader/blob/16f4d3e2988ef765c9d9fd63aa73a5151ee015d7/fdsreader/simulation.py#L936

It references to `self._devices`, which are not available any more. Renaming `_devices` to `devices` seems to solve the problem. Are there any consequences in this fix which I do not see?

Are there any other places in the code which reference to the deleted `Simulation` class variables?

**Comment by lu-kas** [comment]
Thanks! 

Btw, the simple devc example in the example folder does not run. Just as a note.

**Comment by JanVogelsang** [comment]
Fixed in 1.8.7

**Comment by lu-kas** [comment]
Thank you!
