### ISSUE TITLE
slc.to_global error: ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by angzzz** [FireDynamics/fdsreader#51]
Hi, I'm not much of a programmer and want to use the fdsreader to export slice files. A mistake was made. I don't know what's wrong. Could someone help me, please.
 `Traceback (most recent call last):
  File "C:\Users\11734\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-264501c9f462>", line 1, in <module>
    data = slc.to_global(masked=True, fill=np.nan)
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\fdsreader\slcf\slice.py", line 531, in to_global
    grid = np.full((self.n_t, steps['x'], steps['y'], steps['z']), np.nan)
  File "C:\Users\11734\AppData\Roaming\Python\Python39\site-packages\numpy\core\numeric.py", line 343, in full
    a = empty(shape, dtype, order)
ValueError: negative dimensions are not allowed`

**Comment by JanVogelsang** [comment]
Hi, I am certain we will find a solution to your problem. Could you please show me the python script you ran until the error occurred or the commands you entered into your interactive python console?

**Comment by angzzz** [comment]
Thank you for your reply. And these are my codes.

`from matplotlib import cm, pyplot as plt
import numpy as np
import fdsreader as fds

sim = fds.Simulation("C:\Loc_101_A_a-HRR_5_9")
# Examples of data that can be easily accessed
print('slices', sim.slices)
# Slice([2D] quantity=Quantity('TEMPERATURE'), cell_centered=False, extent=Extent([0.00, 48.00] x [0.00, 19.20] x [0.40, 0.40]), extent_dirs=('x', 'y'), orientation=3),
# Slice([2D] quantity=Quantity('TEMPERATURE'), cell_centered=False, extent=Extent([0.00, 48.00] x [0.00, 19.20] x [3.20, 3.20]), extent_dirs=('x', 'y'), orientation=3),
# Slice([2D] quantity=Quantity('TEMPERATURE'), cell_centered=False, extent=Extent([0.00, 48.00] x [0.00, 19.20] x [2.00, 2.00]), extent_dirs=('x', 'y'), orientation=3),
# Slice([2D] quantity=Quantity('TEMPERATURE'), cell_centered=False, extent=Extent([0.00, 48.00] x [0.00, 19.20] x [1.60, 1.60]), extent_dirs=('x', 'y'), orientation=3)])

# Get the slice
slc = sim.slices[4]
# data= slc.to_global(masked=True, fill=np.nan)
data, coordinates = slc.to_global(masked=True, fill=np.nan, return_coordinates=True)`
`data, coordinates = slc.to_global(masked=True, fill=np.nan, return_coordinates=True)`
The last line of code reports the error

And my numpy version == 1.21.4

**Comment by angzzz** [comment]
Thank you for your reply. And these are my codes.

`from matplotlib import cm, pyplot as plt
import numpy as np
import fdsreader as fds

sim = fds.Simulation("C:\Loc_101_A_a-HRR_5_9")
# Examples of data that can be easily accessed
print('slices', sim.slices)
# Slice([2D] quantity=Quantity('TEMPERATURE'), cell_centered=False, extent=Extent([0.00, 48.00] x [0.00, 19.20] x [0.40, 0.40]), extent_dirs=('x', 'y'), orientation=3),
# Slice([2D] quantity=Quantity('TEMPERATURE'), cell_centered=False, extent=Extent([0.00, 48.00] x [0.00, 19.20] x [3.20, 3.20]), extent_dirs=('x', 'y'), orientation=3),
# Slice([2D] quantity=Quantity('TEMPERATURE'), cell_centered=False, extent=Extent([0.00, 48.00] x [0.00, 19.20] x [2.00, 2.00]), extent_dirs=('x', 'y'), orientation=3),
# Slice([2D] quantity=Quantity('TEMPERATURE'), cell_centered=False, extent=Extent([0.00, 48.00] x [0.00, 19.20] x [1.60, 1.60]), extent_dirs=('x', 'y'), orientation=3)])

# Get the slice
slc = sim.slices[4]
# data= slc.to_global(masked=True, fill=np.nan)
data, coordinates = slc.to_global(masked=True, fill=np.nan, return_coordinates=True)`

`data, coordinates = slc.to_global(masked=True, fill=np.nan, return_coordinates=True)`
The last line of code reports the error

And my numpy version == 1.21.4

**Comment by lu-kas** [comment]
If I see it correctly, you try to access the fifth (index 4) slice:
`slc = sim.slices[4]`
Yet, if I'm not wrong, there are only four slices. Could you give it a try and access e.g. the first one 
`slc = sim.slices[0]` ?

**Comment by angzzz** [comment]
> If I see it correctly, you try to access the fifth (index 4) slice: `slc = sim.slices[4]` Yet, if I'm not wrong, there are only four slices. Could you give it a try and access e.g. the first one `slc = sim.slices[0]` ?

Thank you for your reply. As you said I tried to access the first slice`slc = sim.slices[0]`.  But it still reports the same error just like `slc = sim.slices[4]` . Do you have any other solutions, thank you.

**Comment by lu-kas** [comment]
Could you share the FDS or SMV file?

**Comment by JanVogelsang** [comment]
Unfortunately, I can't open the file. When trying to download the file, it simply tells me 'Not found'. Can you verify the upload actually succeeded, and if not try to upload it again or use another way to provide the zip-file?

**Comment by angzzz** [comment]
I tried sending fds and smv files by email. But I'm not sure if you'll get it。         


| |
张璐
|
|
***@***.***
|
---- Replied Message ----
| From | Jan ***@***.***> |
| Date | 12/14/2022 17:23 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [FireDynamics/fdsreader] slc.to_global error: ValueError: negative dimensions are not allowed (Issue #51) |

Unfortunately, I can't open the file. When trying to download the file, it simply tells me 'Not found'. Can you verify the upload actually succeeded, and if not try to upload it again or use another way to provide the zip-file?

**Comment by lu-kas** [comment]
You could also paste the content of the FDS file within tripple `.

**Comment by angzzz** [comment]
[Loc_101_A_a-HRR_5_9.txt](https://github.com/FireDynamics/fdsreader/files/10226619/Loc_101_A_a-HRR_5_9.txt)
Sorry, I don't know what is tripple. But I pasted the fds contents into the txt file.

**Comment by lu-kas** [comment]
For further documentation, this is the error message, if masking is turned on:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/8122581/207570678-b6b180ea-ffa7-4b87-998e-a56525619442.png">

**Comment by angzzz** [comment]
My numpy ==1.21.4
![823f5a937e8d55ba6e774151a65650f](https://user-images.githubusercontent.com/103751224/207587841-fe349dd7-95e4-472a-978e-1f403adb5924.png)
I try to run the example which is you provided' fds_multimesh'. And it also reports the same error. Maybe my packages are inconformity the requirements docs of version.  I'm going to keep trying. THANKS!

**Comment by lu-kas** [comment]
Another question. Which version of FDS do you use?

**Comment by angzzz** [comment]
FDS6. Maybe this error is due to my failure to install several packages such as 'mkL-fft' successfully. And I haven't installed it yet. That's my fault.

**Comment by lu-kas** [comment]
Please be more specific with the FDS version. The mentioned package should have no impact.

**Comment by angzzz** [comment]
FDS6.7.9

**Comment by angzzz** [comment]
Actually I also run files in PyroSim.

**Comment by lu-kas** [comment]
Last try, could you please send me your smv file?

**Comment by angzzz** [comment]
Here is my .smv file. https://github.com/angzzz/fds_files
Could you send me the file that you can run without problems? I would like to try it out. Thank you so much!

**Comment by angzzz** [comment]
Github limits the size of upload files. Would you mind giving me your email address?? I will send you the all relevant documents by email. Thanks.

**Comment by lu-kas** [comment]
You are running a three years old version of FDS, the smv file indicates, that it is not 6.7.9 as you stated above:
```
TITLE
 

FDSVERSION
FDS6.7.1-0-g14cc738-HEAD

ENDF
 Loc_101_A_a-HRR_5_9.end

INPF
 C:\zzz\pyrosim\demo\Loc_101_A_a-HRR_5_9\Loc_101_A_a-HRR_5_9.fds

REVISION
Revisio                                                                                                                                                                                                                                                        
```

Please update to the recent FDS version and rerun your case. I assume, that since three years things have changed in the output format.

I will close the issue. If you still see problems with the newest version of FDS, please reopen it. Good luck.

**Comment by angzzz** [comment]
Thank you so much!
