### ISSUE TITLE
Slice Masking not working due to shape difference

### ISSUE THREAD

**Issue by C-Rogge** [FireDynamics/fdsreader#57]
Another one:

When trying to mask a slice with _to_global(masked=True, fill=np.nan)_ an error occurs which reads as follows:

**ValueError: operands could not be broadcast together with shapes (901,41,41,1) (901,40,40,1) ()** 

...located in line 618 of slice.py (_slc_data = np.where(mask, slc_data, fill)_).

I tried some other simulations with the same result (just differing dimensions, like **(144,1,25,40) (144,1,24,39)** or **(601,79,35,1) (601,78,34,1)**). In a 4th simulation it worked without problems, but i dont really know why. The three simulations i tested while throwing the error dont relate to each other in any way, but somehow the reader seems to get the obstruction mask messed up by one x- and y-cell (at least thats what i would read off that error).

Ideas?

**Comment by lu-kas** [comment]
Could you please create / provide a small FDS input file which leads to the differences? This will make debugging easier. Thanks!

**Comment by r-wrobel** [comment]
Could be the problem solved in #48 (Mask size not changed: cell centered vs. non cell centered slices).

**Comment by C-Rogge** [comment]
@r-wrobel It seems to be just that, thanks for the hint.
@lu-kas For your interest: [fdsreaderTestcase5.fds.txt](https://github.com/FireDynamics/fdsreader/files/10400691/fdsreaderTestcase5.fds.txt) shows the behavior described by @r-wrobel, although already mentioned in the issue linked above. 
I'll close this thread then.
