### ISSUE TITLE
Support for older FDS versions?

### ISSUE THREAD

**Issue by p-lauer** [FireDynamics/fdsreader#60]
Hi!

Same testcase as in issue #59, [test.txt](https://github.com/FireDynamics/fdsreader/files/10459153/test.txt), but now simulated with FDS 6.5.3 (#59 was simulated with the current version).

When I try to load it, I get this error four times and the slice collection is empty.

```
WARNING:root:Module slcf: list index out of range
The error can be safely ignored if not requiring the slcf module. However, please consider to submit an issue on Github including the error message, the stack trace and your FDS input-file so we can reproduce the error and fix it as soon as possible!
```

When I tried it with a more complex case, I also got an error for the bndf module. With the provided test case, there was not such an error message, though loading the bndf data only gives me the values for the first time step.

Since this is an issue with an older version of FDS, is there any chance you'll take a look into this? It would be very useful to be able to compare the results from the same input over different FDS versions.

**Comment by JanVogelsang** [comment]
It is not planned to support older versions of FDS at the moment. There is too much changing in every FDS version, that supporting a new version would require many parts of the package to be redeveloped from the ground up. However, you can always set `fdsreader.settings.DEBUG = True` and try to identify the problem with the version you used in the simulation. Sometimes there are only minor changes required in the fdsreader code to make an older FDS version working.
