### ISSUE TITLE
Slice data structure

### ISSUE THREAD

**Issue by wowwwt** [FireDynamics/fdsreader#62]
Dear all, I had a question when I was extracting slice data. As a beginner, I would like to ask you for advice . When I am printing slice data, the result is shown in the figure below. Combined with [slcf_example_global], I know that the data contains time, coordinates and simulation results. Then how do I know the data represented by different indexes? In addition, what should I do if I want to correspond the simulation result data according to time and coordinates for a 2D slice(that is, output four columns of data, namely time, coordinate 1, coordinate 2 and result)? Oh, btw, it should be my operation problem. The final data doesn't seem to be completely displayed....
![54}$LNL@~03Z3G_8T0L}MFR](https://github.com/FireDynamics/fdsreader/assets/135196399/b2746a21-fc20-4da0-96bd-456b8ec62ff2)

**Comment by wowwwt** [comment]
I have been able to display all the data in the txt file, but I really don't know what these data(data structure) respectively are....

**Comment by JanVogelsang** [comment]
Thanks a lot for your comprehensive answer @dushyant-fire 
@wowwwt Please note that the figure is just intended to give a general overview of all available data structures and does not list all available properties of each class. For a complete list, take a look at the documentation. If anything is unclear, please let us know, so we can improve that part of the documentation.  

Keep in mind that slices lie on any of the X/Y, X/Z, or Y/Z planes, therefore the values you printed are not necessarily the values at the X/Y coordinates, but could also be values at e.g. X/Z coordinates. When you print the coordinates of a slice (i.e., `slc.get_coordinates()`), you will find that one of the dimensions will only contain a single value (in case of 2D slices at least).

**Comment by JanVogelsang** [comment]
@wowwwt I will close this issue for now. Feel free to reopen it if you have any further questions.
