### ISSUE TITLE
how to install fdsreader on linux cluster

### ISSUE THREAD

**Issue by AlanZandie** [FireDynamics/fdsreader#74]
Good day,

I have been engaged with writing a code to optimise FDS simulations, but I need fdsreader to analyse the FDS results. The system I'm using in University of Birmingham, is a linux cluster, I want to clone or install fdsreader on it, but couldnt find a way. Could you please help me with this?
thank you

**Comment by JanVogelsang** [comment]
The fdsreader is conform to standards, which makes it easy to install is in several ways. The most convenient way would be to just run `pip install fdsreader` in your own virtual environment or run `pip install --user fdsreader` to install it using the global interpreter, but in your local home-directory.  
You can also clone the repository `git clone https://github.com/FireDynamics/fdsreader.git` and run `pip install ./fdsreader`. This is equivalent to running `pip install git+https://github.com/FireDynamics/fdsreader.git`.  
The fdsreader was tested on both Windows and Linux-based operating systems and works equally well in both scenarios! Please tell me if I was able to help you already or if there are limitations on your cluster which cause the above solutions to not work in your case.

**Comment by AlanZandie** [comment]
thank you for your swift reply, I believe I installed it on our HPC, but upon recalling in my python code, it still gives the error that it can't find fdsreader. I have copied a draft of the code below, kindly refer to the end of this message for the error which I get:  
python code:
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 28 15:49:18 2024

@author: ADMIN
"""

# Modifying the "minimal_simulation_script.py" to let ACCES optimise the free
# parameters and minimise the error:
#   1. Declare free parameters at the top, given them names and ranges.
#   2. Use the free parameter values to run the simulation like before.

import shutil
import subprocess
import numpy as np
import pandas as pd
import fdsreader
from IPython.display import display
from PIL import Image
import math
import matplotlib
import matplotlib.pyplot as plt


# ACCES PARAMETERS START
import coexist

# Declare the parameters here - give them names and ranges.
# ACCES will modify this section


parameters = coexist.create_parameters(
    ["f1x", "f1y", "f2x", "f2y", "f3x", "f3y", "Q"],
    minimums = [24, 24.4, 24, 24.4, 24, 24.4, 0.76],
    maximums = [68.6, 43.6, 68.6, 43.6, 68.6, 43.6, 1.46],
)


access_id = 0
# ACCES PARAMETERS END

# Let's print the `parameters` object
print("ACCES parameters declared:\n", parameters, "\n")


# Extract ACCES-set parameter values from the parameters table
f1x, f1y, f2x, f2y, f3x, f3y, Q = parameters["value"]


# Copy template directory into a new case
template_directory = "Template"
case_directory = f"Simulations/sim{access_id:0>4}"
shutil.copytree(template_directory, case_directory, dirs_exist_ok=True)


# Modify FDS script to use our ACCES-predicted fan placements
#def modify_fds_script():
fds_script_path = f"{case_directory}/Fan.fds"
with open(fds_script_path) as f:
        script = f.readlines()
    
    
# Find line indices where the fans are defined
fan_line_indices = []
for i in range(len(script)):
        line = script[i]
        if line.startswith("&OBST ID='Fan"):
            fan_line_indices.append(i)
    
assert len(fan_line_indices) == 3
    
InletOutlet_line_indices = []
for j in range(len(script)):
        line = script[j]
        if line.startswith("&VENT ID='Fan"):
            InletOutlet_line_indices.append(j)
    
    
assert len(InletOutlet_line_indices) == 6
    
flowrate_line_indices = []
for m in range(len(script)):
        line = script[m]
        if line.startswith("&HVAC ID='Duct"):
            flowrate_line_indices.append(m)
    
assert len(flowrate_line_indices) == 3
    
# Fan sizes
xlength = 1
ylength = 0.4
    
    
# We take each line where we defined a fan and modify it to contain our ACCES
# values; we do text processing to replace the "XB=..." part
fan_definition = script[fan_line_indices[0]].split()
    
xmin = f1x - xlength / 2
xmax = f1x + xlength / 2
ymin = f1y - ylength / 2
ymax = f1y + ylength / 2
    
fan_definition[3] = f"XB={xmin},{xmax},{ymin},{ymax},1.8,2.2,"
script[fan_line_indices[0]] = " ".join(fan_definition) + "\n"
    
InletOutlet_definition = script[InletOutlet_line_indices[0]].split()
    
Xmax = f1x + xlength / 2
Xmin = Xmax - 0.4
Ymin = f1y - ylength / 2
Ymax = f1y + ylength / 2
    
InletOutlet_definition[4] = f"XB={Xmin},{Xmax},{Ymin},{Ymax},1.8,1.8/"
script[InletOutlet_line_indices[0]] = " ".join(InletOutlet_definition) + "\n"
    
InletOutlet_definition = script[InletOutlet_line_indices[1]].split()
Xmin = f1x - xlength / 2
Xmax = f1x + xlength / 2
Ymin = f1y - ylength / 2
Ymax = f1y + ylength / 2
InletOutlet_definition[4] = f"XB={Xmin},{Xmin},{Ymin},{Ymax},1.8,2.2,"
script[InletOutlet_line_indices[1]] = " ".join(InletOutlet_definition) + "\n" 
    
    
    
fan_definition = script[fan_line_indices[1]].split()
xmin = f2x - xlength / 2
xmax = f2x + xlength / 2
ymin = f2y - ylength / 2
ymax = f2y + ylength / 2
fan_definition[3] = f"XB={xmin},{xmax},{ymin},{ymax},1.8,2.2,"
script[fan_line_indices[1]] = " ".join(fan_definition) + "\n"
    
InletOutlet_definition = script[InletOutlet_line_indices[2]].split()
    
Xmax = f2x + xlength / 2
Xmin = Xmax - 0.4
Ymin = f2y - ylength / 2
Ymax = f2y + ylength / 2
    
InletOutlet_definition[4] = f"XB={Xmin},{Xmax},{Ymin},{Ymax},1.8,1.8/"
script[InletOutlet_line_indices[2]] = " ".join(InletOutlet_definition) + "\n"
    
InletOutlet_definition = script[InletOutlet_line_indices[3]].split()
Xmin = f2x - xlength / 2
Xmax = f2x + xlength / 2
Ymin = f2y - ylength / 2
Ymax = f2y + ylength / 2
InletOutlet_definition[4] = f"XB={Xmin},{Xmin},{Ymin},{Ymax},1.8,2.2,"
script[InletOutlet_line_indices[3]] = " ".join(InletOutlet_definition) + "\n"
    
    
fan_definition = script[fan_line_indices[2]].split()
xmin = f3x - xlength / 2
xmax = f3x + xlength / 2
ymin = f3y - ylength / 2
ymax = f3y + ylength / 2
fan_definition[3] = f"XB={xmin},{xmax},{ymin},{ymax},1.8,2.2,"
script[fan_line_indices[2]] = " ".join(fan_definition) + "\n"
    
InletOutlet_definition = script[InletOutlet_line_indices[4]].split()
    
Xmax = f3x + xlength / 2
Xmin = Xmax - 0.4
Ymin = f3y - ylength / 2
Ymax = f3y + ylength / 2
    
InletOutlet_definition[4] = f"XB={Xmin},{Xmax},{Ymin},{Ymax},1.8,1.8/"
script[InletOutlet_line_indices[4]] = " ".join(InletOutlet_definition) + "\n"
    
InletOutlet_definition = script[InletOutlet_line_indices[5]].split()
Xmin = f3x - xlength / 2
Xmax = f3x + xlength / 2
Ymin = f3y - ylength / 2
Ymax = f3y + ylength / 2
InletOutlet_definition[4] = f"XB={Xmin},{Xmin},{Ymin},{Ymax},1.8,2.2,"
script[InletOutlet_line_indices[5]] = " ".join(InletOutlet_definition) + "\n"
    
# the line in where the flowrate changes, the Q value is optimised   

for i in range(len(flowrate_line_indices)):
        flowrate_definition = script[flowrate_line_indices[i]].split()
        flowrate_definition[4] = f"VOLUME_FLOW={Q},"
        script[flowrate_line_indices[i]] = " ".join(flowrate_definition) + "\n" 

    
    
    # Overwrite the case FDS script with our modified values
with open(fds_script_path, "w") as f:
        f.writelines(script)

# Check fans are all placed further away than this
def check_fan_distances():
    min_distance = 4 
    fan_centers = np.array([
        [f1x, f1y],
        [f2x, f2y],
        [f3x, f3y],
    ])
    for i in range(0, len(fan_centers) - 1):
        for j in range(i + 1, len(fan_centers)):
            distance = np.linalg.norm(fan_centers[i] - fan_centers[j])
            if distance < min_distance:
                print((
                    f"Fans {i} and {j} (distance={distance}) are closer than "
                    f"min_distance={min_distance}! Aborting..."
                ))
                return False
    return True



if not check_fan_distances() == True:
    # Some fans are too close
    velocity = np.inf
    temperature = np.inf
    visibility = np.inf
    
else:
    # Launch simulation and wait for it to finish
    subprocess.run(["bash", "run_fds_case.sh", case_directory], check=True)

    # Extract the simulated values we want to optimise
    
    path_to_data = f"{case_directory}"
    sim = fdsreader.Simulation(path_to_data)
    # the data from which the slices (contours) are made of are extracted here 
    slc_u = sim.slices.filter_by_quantity('VELOCITY').get_nearest(z=1.6)
    slc_v = sim.slices.filter_by_quantity('SOOT VISIBILITY').get_nearest(z=1.6)
    slc_T = sim.slices.filter_by_quantity('TEMPERATURE').get_nearest(z=1.6)
    
    # the last time at which the simulation was saved is recalled
    it = slc_v.get_nearest_timestep(time=300)
    
    # the data from all the meshes are merged here into one collection 
    gslice_v, gcoord_v = slc_v.to_global(return_coordinates=True)
    gslice_u, gcoord_u = slc_u.to_global(return_coordinates=True)
    gslice_T, gcoord_T = slc_T.to_global(return_coordinates=True)
    
    # the slice data at that particular time is recalled here
    u = gslice_u[it]
    v = gslice_v[it]
    T = gslice_T[it]
    
    # any Nan values are replaced with zero "0" for all the slices
    u = np.nan_to_num(u, nan=0)
    v = np.nan_to_num(v, nan=0)
    T = np.nan_to_num(T, nan=0)
    
    # the conditions under which the simulations must comply to are defined
    # velocity
    condition_u1=u > 0
    condition_u2=u < 0.1
    # visibility
    condition_v1=v > 0
    condition_v2=v < 12
    # temperature
    condition_T=T > 50
            
    limit_u = np.where(condition_u1 & condition_u2)
    limit_v = np.where(condition_v1 & condition_v2)
    limit_T = np.where(condition_T)

    velocity_ratio = (u[limit_u].size)/(gslice_u[1].size)
    min_velocity_ratio = 0.10
    if (velocity_ratio > min_velocity_ratio):
        velocity = np.inf
    else:
        velocity = u[limit_u]
    
   
    visibility_ratio = (u[limit_v].size)/(gslice_v[1].size)
    min_visibility_ratio = 0.10
    if (visibility_ratio > min_visibility_ratio):
        visibility = np.inf
    else:
        visibility = v[limit_v]
        
    temperature_ratio = (u[limit_T].size)/(gslice_T[1].size)
    min_temperature_ratio = 0.10
    if (temperature_ratio > min_temperature_ratio):
        temperature = np.inf
    else:
        temperature = T[limit_T]    
     
    # I have defined the areas where the tanability criteria are not met
    # and the error will try to minimise those regions, unless they are 
    # above certain thresholds, in which 'inf' is considered for that case.
error = [velocity, temperature, visibility, Q] 
----------------------------------------------------------------------------
the output file gives me this:
GCCcore/12.2.0
zlib/1.2.12-GCCcore-12.2.0
binutils/2.39-GCCcore-12.2.0
GCC/12.2.0
numactl/2.0.16-GCCcore-12.2.0
XZ/5.2.7-GCCcore-12.2.0
libxml2/2.10.3-GCCcore-12.2.0
libpciaccess/0.17-GCCcore-12.2.0
hwloc/2.8.0-GCCcore-12.2.0
OpenSSL/1.1
libevent/2.1.12-GCCcore-12.2.0
UCX/1.13.1-GCCcore-12.2.0
libfabric/1.16.1-GCCcore-12.2.0
PMIx/4.2.2-GCCcore-12.2.0
UCC/1.1.0-GCCcore-12.2.0
OpenMPI/4.1.4-GCC-12.2.0
OpenBLAS/0.3.21-GCC-12.2.0
FlexiBLAS/3.2.1-GCC-12.2.0
FFTW/3.3.10-GCC-12.2.0
gompi/2022b
FFTW.MPI/3.3.10-gompi-2022b
ScaLAPACK/2.2.0-gompi-2022b-fb
foss/2022b
bzip2/1.0.8-GCCcore-12.2.0
ncurses/6.3-GCCcore-12.2.0
libreadline/8.2-GCCcore-12.2.0
ncurses/6.3-GCCcore-12.2.0
Tcl/8.6.12-GCCcore-12.2.0
SQLite/3.39.4-GCCcore-12.2.0
GMP/6.2.1-GCCcore-12.2.0
libffi/3.4.4-GCCcore-12.2.0
Python/3.10.8-GCCcore-12.2.0
gfbf/2022b
pybind11/2.10.3-GCCcore-12.2.0
SciPy-bundle/2023.02-gfbf-2022b
libpng/1.6.38-GCCcore-12.2.0
Brotli/1.0.9-GCCcore-12.2.0
freetype/2.12.1-GCCcore-12.2.0
expat/2.4.9-GCCcore-12.2.0
util-linux/2.38.1-GCCcore-12.2.0
fontconfig/2.14.1-GCCcore-12.2.0
xorg-macros/1.19.3-GCCcore-12.2.0
X11/20221110-GCCcore-12.2.0
Tk/8.6.12-GCCcore-12.2.0
Tkinter/3.10.8-GCCcore-12.2.0
NASM/2.15.05-GCCcore-12.2.0
libjpeg-turbo/2.1.4-GCCcore-12.2.0
jbigkit/2.1-GCCcore-12.2.0
gzip/1.12-GCCcore-12.2.0
lz4/1.9.4-GCCcore-12.2.0
zstd/1.5.2-GCCcore-12.2.0
libdeflate/1.15-GCCcore-12.2.0
LibTIFF/4.4.0-GCCcore-12.2.0
Pillow/9.4.0-GCCcore-12.2.0
Qhull/2020.2-GCCcore-12.2.0
matplotlib/3.7.0-gfbf-2022b
cma/3.3.0-foss-2022b
plotly.py/5.13.1-GCCcore-12.2.0
tqdm/4.64.1-GCCcore-12.2.0
coexist/0.3.2-foss-2022b
Traceback (most recent call last):
  File "/rds/projects/j/jangim-fire-smoke-safety/allen/runCases/ACCES/access_seed42/access_script.py", line 50, in <module>
    import fdsreader
ModuleNotFoundError: No module named 'fdsreader'
----------------------------------------------------------------

**Comment by AlanZandie** [comment]
Also, I checked installing it again, but it seems it is already installed as I get:

Requirement already satisfied: fdsreader in /rds/homes/z/zandiem/.local/lib/python3.6/site-packages
Requirement already satisfied: incremental in /rds/homes/z/zandiem/.local/lib/python3.6/site-packages (from fdsreader)
Requirement already satisfied: numpy in /rds/homes/z/zandiem/.local/lib/python3.6/site-packages (from fdsreader)
Requirement already satisfied: typing_extensions in /rds/homes/z/zandiem/.local/lib/python3.6/site-packages (from fdsreader)

**Comment by JanVogelsang** [comment]
I'm afraid I can't help you with this issue, you might want to contact your system administrator instead. If you installed the fdsreader, your python interpreter should find it.  
How do you invoke the script? Do you just run `python access_script.py`? The python interpreter doesn't seem to look in the site-packages directory you listed (`/rds/homes/z/zandiem/.local/lib/python3.6/site-packages`).

**Comment by AlanZandie** [comment]
Thank you for your comments, I believe I took care of, the issue was that there were two versions of Python installed on our cluster, and it was searching through wrong module library. Also, given that I was not allowed to make changes on the cluster, I had to make my own repository and specify it using PATH, I did the same for PYTHONPATH, to look into the directory I saved my modules in, particularly fdsreader.
Thank you,
