### ISSUE TITLE
Warning regarding module vent when assessing slice

### ISSUE THREAD

**Issue by FelixBickert** [FireDynamics/fdsreader#78]
Hi,

when using fdsreader to assess a temperature slice, the following warning message appears:

WARNING:root:Module vents: could not convert string to float: '!'
The error can be safely ignored if not requiring the vents module. However, please consider to submit an issue on Github including the error message, the stack trace and your FDS input-file so we can reproduce the error and fix it as soon as possible!_

There is only one frame available, which outputs a homogeneous 20°C temperature field.

I attached the fds case and my ipynb and would be very pleased about help.

--
FDS version: FDS-6.9.1-0-g889da6a-release
fdsreader version: 1.10.4

[testcase.zip](https://github.com/user-attachments/files/15637650/testcase.zip)

**Comment by dushyant-fire** [comment]
Any updates on whether you could fix the issue? I do not get the warnings, but see only the first (0.0s) frame. I wonder if FDS outputs for slice files have changed which affects this.

**Comment by FelixBickert** [comment]
Thank you for your reply. In fact, everything works with FDS version 6.8.0, but no longer from 6.9.0. Issue #73 shows that the problem seems to be known.
