### ISSUE TITLE
fdsreader for FDS 6.9

### ISSUE THREAD

**Issue by xixiuqi** [FireDynamics/fdsreader#85]
Hi, 

Recently, I have been attempting to use the Ffdsreader for reading slice files in FDS. However, with FDS 6.9, it seems that only the slice at 0 seconds is being read from the simulation, which I believe has also been reported as an issue.

https://github.com/FireDynamics/fdsreader/issues/78#issuecomment-2176501859

Thanks so much if any ideas and suggestions can be provided.

**Comment by lu-kas** [comment]
I'm on it. Sorry for the inconvenience.

**Comment by lu-kas** [comment]
Hey! Could you please give it a try with the recent version?

**Comment by xixiuqi** [comment]
This one works! Thanks so much for maintaining such a great and useful tool!

**Comment by xixiuqi** [comment]
> Hi,
> 
> Recently, I have been attempting to use the Ffdsreader for reading slice files in FDS. However, with FDS 6.9, it seems that only the slice at 0 seconds is being read from the simulation, which I believe has also been reported as an issue.
> 
> [#78 (comment)](https://github.com/FireDynamics/fdsreader/issues/78#issuecomment-2176501859)
> 
> Thanks so much if any ideas and suggestions can be provided.

Hello,

Thanks again for updating the slice reading. It seems that FDS team also changed the data structure of boundary data (.bf) files as well in FDS 6.9. Could you check that?

Xiuqi

**Comment by amarcozzi** [comment]
I still have an open PR #79 that addresses this issue. It's been many months, and many nudges, since I opened the PR. Can you please at least take a look and decide on a fix for this issue?

**Comment by lu-kas** [comment]
Hi. Thanks @amarcozzi ! Based on your PR, I have created an update. The reading of boundary files should work again. Could you please have a try with version 1.11.6?

**Comment by xixiuqi** [comment]
version 1.11.6 can work for .bf files now. Thanks so much!
