### ISSUE TITLE
fdsreader 1.11.5 - variable reader_version

### ISSUE THREAD

**Issue by gjaeger** [FireDynamics/fdsreader#86]
After updating to 1.11.5, I get the following output when calling the variable ``sim.reader_version``:
```
Version('fdsreader', 1, 10, 3)
```
This is confusing. The version check (pip) is correct (1.11.5):
```
$ pip show fdsreader 
...
Name: fdsreader
Version: 1.11.5
```

**Comment by m-fehr** [comment]
Thank you for highlighting this issue! We've already prepared a fix for the internal version mismatch, and we’ll be releasing it along with other updates we're currently working on within the next few days.

**Comment by m-fehr** [comment]
Hi,
sorry for the delay but the version mismatch should be fixed now.

**Comment by gjaeger** [comment]
@m-fehr perfect, it works
